// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

interface DeliverydataDocumentData {}

/**
 * deliverydata document from Prismic
 *
 * - **API ID**: `deliverydata`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DeliverydataDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DeliverydataDocumentData>,
    "deliverydata",
    Lang
  >;

export type AllDocumentTypes = DeliverydataDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      DeliverydataDocument,
      DeliverydataDocumentData,
      AllDocumentTypes,
    };
  }
}
